// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package tracks is a generated GoMock package.
package tracks

import (
	context "context"
	reflect "reflect"

	trackactivities "github.com/YugaAI/MusicCatalog/internal/models/trackactivities"
	spotify "github.com/YugaAI/MusicCatalog/internal/repository/spotify"
	gomock "github.com/golang/mock/gomock"
)

// MockSpotifyOutbound is a mock of SpotifyOutbound interface.
type MockSpotifyOutbound struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyOutboundMockRecorder
}

// MockSpotifyOutboundMockRecorder is the mock recorder for MockSpotifyOutbound.
type MockSpotifyOutboundMockRecorder struct {
	mock *MockSpotifyOutbound
}

// NewMockSpotifyOutbound creates a new mock instance.
func NewMockSpotifyOutbound(ctrl *gomock.Controller) *MockSpotifyOutbound {
	mock := &MockSpotifyOutbound{ctrl: ctrl}
	mock.recorder = &MockSpotifyOutboundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyOutbound) EXPECT() *MockSpotifyOutboundMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSpotifyOutbound) Search(ctx context.Context, query string, limit, offsite int) (*spotify.SpotifySearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offsite)
	ret0, _ := ret[0].(*spotify.SpotifySearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSpotifyOutboundMockRecorder) Search(ctx, query, limit, offsite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpotifyOutbound)(nil).Search), ctx, query, limit, offsite)
}

// MockTracksActivityRepository is a mock of TracksActivityRepository interface.
type MockTracksActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTracksActivityRepositoryMockRecorder
}

// MockTracksActivityRepositoryMockRecorder is the mock recorder for MockTracksActivityRepository.
type MockTracksActivityRepositoryMockRecorder struct {
	mock *MockTracksActivityRepository
}

// NewMockTracksActivityRepository creates a new mock instance.
func NewMockTracksActivityRepository(ctrl *gomock.Controller) *MockTracksActivityRepository {
	mock := &MockTracksActivityRepository{ctrl: ctrl}
	mock.recorder = &MockTracksActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracksActivityRepository) EXPECT() *MockTracksActivityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTracksActivityRepository) Create(ctx context.Context, model trackactivities.TrackActivities) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTracksActivityRepositoryMockRecorder) Create(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTracksActivityRepository)(nil).Create), ctx, model)
}

// Get mocks base method.
func (m *MockTracksActivityRepository) Get(ctx context.Context, userID uint, spotifyID string) (*trackactivities.TrackActivities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, spotifyID)
	ret0, _ := ret[0].(*trackactivities.TrackActivities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTracksActivityRepositoryMockRecorder) Get(ctx, userID, spotifyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTracksActivityRepository)(nil).Get), ctx, userID, spotifyID)
}

// GetBulkSpotifyID mocks base method.
func (m *MockTracksActivityRepository) GetBulkSpotifyID(ctx context.Context, userID uint, spotifyIDs []string) (map[string]trackactivities.TrackActivities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkSpotifyID", ctx, userID, spotifyIDs)
	ret0, _ := ret[0].(map[string]trackactivities.TrackActivities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkSpotifyID indicates an expected call of GetBulkSpotifyID.
func (mr *MockTracksActivityRepositoryMockRecorder) GetBulkSpotifyID(ctx, userID, spotifyIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkSpotifyID", reflect.TypeOf((*MockTracksActivityRepository)(nil).GetBulkSpotifyID), ctx, userID, spotifyIDs)
}

// Update mocks base method.
func (m *MockTracksActivityRepository) Update(ctx context.Context, model trackactivities.TrackActivities) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTracksActivityRepositoryMockRecorder) Update(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTracksActivityRepository)(nil).Update), ctx, model)
}
