// Code generated by MockGen. DO NOT EDIT.
// Source: hendler.go

// Package tracks is a generated GoMock package.
package tracks

import (
	context "context"
	reflect "reflect"

	spotify "github.com/YugaAI/MusicCatalog/internal/models/spotify"
	trackactivities "github.com/YugaAI/MusicCatalog/internal/models/trackactivities"
	gomock "github.com/golang/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *Mockservice) Search(ctx context.Context, query string, pageSize, pageIndex int, userID uint) (*spotify.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, pageSize, pageIndex, userID)
	ret0, _ := ret[0].(*spotify.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockserviceMockRecorder) Search(ctx, query, pageSize, pageIndex, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*Mockservice)(nil).Search), ctx, query, pageSize, pageIndex, userID)
}

// UpsertTrackActivity mocks base method.
func (m *Mockservice) UpsertTrackActivity(ctx context.Context, userID uint, request trackactivities.TrackActivitiesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTrackActivity", ctx, userID, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTrackActivity indicates an expected call of UpsertTrackActivity.
func (mr *MockserviceMockRecorder) UpsertTrackActivity(ctx, userID, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTrackActivity", reflect.TypeOf((*Mockservice)(nil).UpsertTrackActivity), ctx, userID, request)
}
