name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # wajib agar semantic-release bisa membaca semua tag

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest

      - name: Install Node.js (Semantic Release)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: |
          npm install -g semantic-release \
            @semantic-release/git \
            @semantic-release/changelog \
            @semantic-release/commit-analyzer \
            @semantic-release/exec \
            @semantic-release/release-notes-generator \
            @semantic-release/github

      - name: Run Release Automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
